version: "3.7"

services:

  geth:
    image: geth-node:stable
    build:
      context: ./geth
    container_name: ethereum-geth-node
    ports:
      - "8545:8545"
      - "8546:8546"
    restart: unless-stopped
    volumes:
      - geth-data:/root

volumes:
  geth-data:
